travis:
  secure:
    BINSTAR_TOKEN: ZV7oxEp6YRRsqvDybb0Ojf6r/mi48Buc6F70utDuw70HwGrIeO705T8XMvSiohGRf5TCs7TsdIs2Qccjajc2SF/CCGhy2M8JZ0RgI3+k5o3RLjzcoHk8/yd2gnXA5VowgteYHjwsNcS6xktc3/FbfHVP2GP3yAOYLzyLOGdS6jex/CxHSJGVwTqES8b2LzO3rX19sSbIZaKVyK+vHf4Afy+MFdQRXLYypl9vrRXwOqOIwSVWOU9vqBtBWKrtQNJBtjJtbEBNgnH/uNw3uiPPs2iUI+9K08LtFAmjPDpnn946uQhOu641NxV5/FyxgWPDhuyr6wS5n4Bjd0EejEXskgV3Ww9DHh0CyNHLQNcEOLk8xSy5yQbg/4SCUEdtJ7AI/QXcFRHuvLSOExT5W9mbK5LWyILBekwyQVfUfbDqXEq/170tDSYq7047rXAfQWC7CUtsS2qYchrMrCGjzkiXsUiB+2iIuiNtkQJZtugi8/booeibPGRltgtcn+Mv4p8ta+3qZRihBUPGCMPeab8e5wOOA7O+2HYG0S4Z6Ru6Jfy6Bhlc7tlsFhiLJY42XICDFj5Lf4aKnGahGCgs+kQGtILy9N6TPlI7iY2gB/Zh7CUOUwSskiJ2ok1ipV2qwda6vgQ0nAIQ7icL+DYG4FhoWHXm9RchKXdcNNsTqP8aNQQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
